channels:
- conda-forge
dependencies:
- python=3.12.7
- pip<=24.2
- pip:
  - mlflow==2.22.0
  - cloudpickle==3.0.0
  - lz4==4.3.2
  - numpy==1.26.4
  - psutil==5.9.0
  - scikit-learn==1.5.1
  - scipy==1.13.1
name: mlflow-env
